---
- name: Install Prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink my dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .tmux.conf
    - .zshrc
    - .zpreztorc
    - .zprofile

- name: Symlink my config files 
  file: src=~/dotfiles/config/{{ item }}
        dest=~/.config/{{ item }}
        state=link
        force=yes
  with_items:
    - nvim
    - karabiner

- name: Clone tmux plugins
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Install/update tmux plugins
  command: ~/.tmux/plugins/tpm/bin/update_plugins all

  #- name: Clone Dein 
  #git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
  #- name: Install/update VIM plugins
  #command: vim +PluginInstall! +qall
