---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap Neovim
  homebrew_tap: tap=neovim/neovim state=present

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - python
    - python3
    - vim
    - neovim
    - wget
    - zsh
    - tmux
    - zsh-completions
    - fzf
