---
- import_tasks: homebrew.yml

- name: osx | disable Dashboard
  shell: defaults write com.apple.dashboard mcx-disabled -bool true

- name: osx | save screenshots to Downloads
  shell: defaults write com.apple.screencapture location ~/Downloads
